name: admin_desktop
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.7.4+17

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  intl: ^0.19.0
  msix: ^3.12.1
  lottie: ^3.1.2
  get_it: ^7.7.0
  shimmer: ^3.0.0
  provider: ^6.0.5
  fl_chart: ^0.69.0
  auto_route: ^9.2.0
  geolocator: ^13.0.1
  top_snackbar_flutter: ^3.0.0+1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  file_picker: ^8.0.5
  dotted_border: ^2.1.0
  osm_nominatim: ^3.0.0
  flutter_remix: ^0.0.3
  remixicon: ^1.3.0
  image_cropper: ^9.0.0
  url_launcher: ^6.1.10
  flutter_svg: ^2.0.10+1
  multi_dropdown: ^2.0.0
  auto_size_text: ^3.0.0
  flutter_isolate: ^2.0.4
  pull_to_refresh: ^2.0.0
  bitsdojo_window: ^0.1.5
  flutter_slidable: ^3.1.0
  flutter_riverpod: ^2.5.1
  connectivity_plus: ^6.1.2
  percent_indicator: ^4.2.3
  freezed_annotation: ^2.1.0
  flutter_screenutil: ^5.8.1
  shared_preferences: ^2.0.15
  google_maps_flutter: ^2.7.0
  google_maps_flutter_web: ^0.5.10
  drag_and_drop_lists: ^0.4.1
  google_sign_in: ^6.2.1
  either_dart: ^1.0.0
  cached_network_image: ^3.3.0
  proste_indexed_stack: ^0.2.4
  calendar_date_picker2: ^1.1.5
  flutter_esc_pos_utils: ^1.0.0
  flutter_advanced_switch: ^3.0.1
  flutter_staggered_animations: ^1.1.1
  network_info_plus: ^6.0.2
  ping_discover_network_forked: ^0.0.1
  rxdart: ^0.28.0
  screen_retriever: ^0.2.0
  win32: ^5.8.0
  ffi: ^2.0.1
  window_manager: ^0.4.3
  flutter_beep: ^1.0.0
  flutter_blue_plus: ^1.33.4
  shelf: ^1.4.0
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^3.0.1
  webview_flutter: ^4.8.0
  webview_windows: ^0.4.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  cupertino_icons: ^1.0.6
  #flutter_yoco: ^1.0.2

  #firebase:
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  audioplayers: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.9
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.0.0



flutter_icons:
  android: true
  ios: true
  mac: true
  remove_alpha_ios: true
  image_path: 'assets/images/png/app_logo.png'

  msix_config:
    display_name: JuvoPOS
    publisher_display_name: Juvo Platforms
    identity_name: app.juvo.pos
    msix_version: 1.0.0.0
    logo_path: D:\post_app_foodyman-main\post_app_foodyman\assets\images\png\app_logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/svg/
    - assets/lottie/
    - assets/
    - assets/images/
    - assets/audio/
    #- assets/sounds/tap.mp3
    - assets/sounds/tap.wav
    - assets/sounds/wrong.wav
  fonts:
    - family: FlutterRemix
      fonts:
        - asset: packages/flutter_remix/fonts/FlutterRemix.ttf

